[features]
seeds = false
[programs.localnet]
subrina_protocol = "FWrg3R4FVkLDaxcA6uYsGhV4hDpKWxu7AgoFUuWGKYUP"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/irshad/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
