[features]
seeds = false
[programs.localnet]
subrina_protocol = "9Byr46LJDyAgDXzvAUmkpDzxjiwjC2rBuUn1m2AGC4oh"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/irshad/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
